from os import system

file = open("video.c", "w")
file.write("#include <stdio.h>\n")
file.write("#include <stdlib.h>\n")
file.write("#include <time.h>\n")
file.write("#include <unistd.h>\n")
file.write("#include <string.h>\n\n")
file.write("int main(void) {\n")
file.write("    for(;;) {\n")
file.write("    	system(\"clear\");\n")
file.write("	srand(time(0));\n\n")
file.write("    	int r = rand() % 6;\n")
vid1 = input("Enter your first video's name, make sure to include the extension: ")
file.write("    	char vid1[32] = \"vlc ")
file.write(vid1)
file.write("\";\n")
vid2 = input("Enter your second video's name, make sure to include the extension: ")
file.write("    	char vid2[32] = \"vlc ")
file.write(vid2)
file.write("\";\n")
vid3 = input("Enter your third video's name, make sure to include the extension: ")
file.write("	char vid3[32] = \"vlc ")
file.write(vid3)
file.write("\";\n")
vid4 = input("Enter your fourth video's name, make sure to include the extension: ")
file.write("    	char vid4[32] = \"vlc ")
file.write(vid4)
file.write("\";\n")
vid5 = input("Enter your fifth video's name, make sure to include the extension: ")
file.write("    	char vid5[32] = \"vlc ")
file.write(vid5)
file.write("\";\n")
vid6 = input("Enter your sixth video's name, make sure to include the extension: ")
file.write("    	char vid6[32] = \"vlc ")
file.write(vid6)
file.write("\";\n")
file.write("    	char exit;\n\n")
file.write("	    if(r == 0) {\n")
file.write("	    	printf(\"Now Playing:\'%.*s\'\", 32, vid1 + 4);\n")
file.write("	    	sleep(5);\n")
file.write("	    	system(vid1);\n")
file.write("	    	exit = getchar();\n")
file.write("	    	if(exit == 0x0A) {\n")
file.write("	    		break;\n")
file.write("	    	}\n")
file.write("	    } else if(r == 1) {\n")
file.write("	    	printf(\"Now Playing:\'%.*s\'\", 32, vid2 + 4);\n")
file.write("	    	sleep(5);\n")
file.write("	    	system(vid2);\n")
file.write("	    	exit = getchar();\n")
file.write("	    	if(exit == 0x0A) {\n")
file.write("	    		break;\n")
file.write("	    	}\n")
file.write("	    } else if(r == 2) {\n")
file.write("	    	printf(\"Now Playing:\'%.*s\'\", 32, vid3 + 4);\n")
file.write("	    	sleep(5);\n")
file.write("	    	system(vid3);\n")
file.write("	    	exit = getchar();\n")
file.write("	    	if(exit == 0x0A) {\n")
file.write("	    		break;\n")
file.write("	    	}\n")
file.write("	    } else if(r == 3) {\n")
file.write("	    	printf(\"Now Playing:\'%.*s\'\", 32, vid4 + 4);\n")
file.write("	    	sleep(5);\n")
file.write("	    	system(vid4);\n")
file.write("	    	exit = getchar();\n")
file.write("	    	if(exit == 0x0A) {\n")
file.write("	    		break;\n")
file.write("	    	}\n")
file.write("	    } else if(r == 4) {\n")
file.write("	    	printf(\"Now Playing:\'%.*s\'\", 32, vid5 + 4);\n")
file.write("	    	sleep(5);\n")
file.write("	    	system(vid5);\n")
file.write("	    	exit = getchar();\n")
file.write("	    	if(exit == 0x0A) {\n")
file.write("	    		break;\n")
file.write("	    	}\n")
file.write("	    } else if(r == 5) {\n")
file.write("	    	printf(\"Now Playing:\'%.*s\'\", 32, vid6 + 4);\n")
file.write("	    	sleep(5);\n")
file.write("	    	system(vid6);\n")
file.write("	    	exit = getchar();\n")
file.write("	    	if(exit == 0x0A) {\n")
file.write("	    		break;\n")
file.write("	    	}\n")
file.write("	    } else {\n")
file.write("	    	printf(\"No Video Present\");\n")
file.write("	    	exit = getchar();\n")
file.write("	    	if(exit == 0x0A) {\n")
file.write("	    		break;\n")
file.write("	    	}\n")
file.write("	    }\n")
file.write("	}\n")
file.write("    return 0;\n")
file.write("}\n")

file.close()

system("gcc video.c -o video")
